### ISSUE TITLE
Fix deleting post/thread bug.

### ISSUE THREAD

**Issue by evanlinjin** [evanlinjin/bbs#2]

**Comment by tectiv3** [comment]
You mean deleting of imported threads? And them reappearing after being deleted?

**Comment by evanlinjin** [comment]
Also, I thought you said that there was a problem when trying to remove the `ThreadPage`? Like it couldn't find it or something?

**Comment by tectiv3** [comment]
nope, that I figured out

**Comment by evanlinjin** [comment]
Sweet awesome! Thanks :)
